package com.dne.ctrip.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * BMdClaimMailPolicy generated by MyEclipse - Hibernate Tools
 */
@Getter
@Setter
public class BatchCompleteMail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long mailId;// MAIL_ID

	private String mailSender;// MAIL_SENDER

	private String mailFrom;// MAIL_FROM

	private String mailTo;// MAIL_TO

	private String mailCc;// MAIL_CC

	private String mailBcc;// MAIL_BCC

	private String mailSubject;// MAIL_SUBJECT

	private String mailBody;// MAIL_BODY

	private String mailAttachment;// MAIL_ATTACHMENT

	private Date createDate;// CREATE_DATE

	private Date sentDate;// SENT_DATE

	private String isSent;// IS_SENT

	private Integer wrongtimes;// WRONG_TIMES

	private String moblieApprovalId;// MOBLIE_APPROVAL_ID

	private String missMailAddress;// MISS_MAIL_ADDRESS

}