package com.dne.ctrip.entity;

import java.util.Date;

/**
 * BMdClaimMailPolicy generated by MyEclipse - Hibernate Tools
 */

public class BatchCompleteMail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long mailId;// MAIL_ID

	private String mailSender;// MAIL_SENDER

	private String mailFrom;// MAIL_FROM

	private String mailTo;// MAIL_TO

	private String mailCc;// MAIL_CC

	private String mailBcc;// MAIL_BCC

	private String mailSubject;// MAIL_SUBJECT

	private String mailBody;// MAIL_BODY

	private String mailAttachment;// MAIL_ATTACHMENT

	private Date createDate;// CREATE_DATE

	private Date sentDate;// SENT_DATE

	private String isSent;// IS_SENT

	private Integer wrongtimes;// WRONG_TIMES

	private String moblieApprovalId;// MOBLIE_APPROVAL_ID

	private String missMailAddress;// MISS_MAIL_ADDRESS

	public Long getMailId() {
		return mailId;
	}

	public void setMailId(Long mailId) {
		this.mailId = mailId;
	}

	public String getMailSender() {
		return mailSender;
	}

	public void setMailSender(String mailSender) {
		this.mailSender = mailSender;
	}

	public String getMailFrom() {
		return mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	public String getMailTo() {
		return mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	public String getMailCc() {
		return mailCc;
	}

	public void setMailCc(String mailCc) {
		this.mailCc = mailCc;
	}

	public String getMailBcc() {
		return mailBcc;
	}

	public void setMailBcc(String mailBcc) {
		this.mailBcc = mailBcc;
	}

	public String getMailSubject() {
		return mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

	public String getMailBody() {
		return mailBody;
	}

	public void setMailBody(String mailBody) {
		this.mailBody = mailBody;
	}

	public String getMailAttachment() {
		return mailAttachment;
	}

	public void setMailAttachment(String mailAttachment) {
		this.mailAttachment = mailAttachment;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getSentDate() {
		return sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	public String getIsSent() {
		return isSent;
	}

	public void setIsSent(String isSent) {
		this.isSent = isSent;
	}

	public Integer getWrongtimes() {
		return wrongtimes;
	}

	public void setWrongtimes(Integer wrongtimes) {
		this.wrongtimes = wrongtimes;
	}

	public String getMoblieApprovalId() {
		return moblieApprovalId;
	}

	public void setMoblieApprovalId(String moblieApprovalId) {
		this.moblieApprovalId = moblieApprovalId;
	}

	public String getMissMailAddress() {
		return missMailAddress;
	}

	public void setMissMailAddress(String missMailAddress) {
		this.missMailAddress = missMailAddress;
	}

}