package com.dne.ctrip.entity;

import com.dne.core.basic.entity.BaseEntity;

/**
 * BMdClaimMailPolicy generated by MyEclipse - Hibernate Tools
 */

public class CommonMailPolicy extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long mailId;

	private String processType;

	private String mailType;

	private String subject;

	private String tpath;

	private String template;

	private String mailTo;

	public CommonMailPolicy() {

	}

	public Long getMailId() {
		return this.mailId;
	}

	public void setMailId(Long mailId) {
		this.mailId = mailId;
	}

	public String getMailType() {
		return this.mailType;
	}

	public void setMailType(String mailType) {
		this.mailType = mailType;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	public String getProcessType() {
		return processType;
	}

	public void setProcessType(String processType) {
		this.processType = processType;
	}

	public String getTpath() {
		return tpath;
	}

	public void setTpath(String tpath) {
		this.tpath = tpath;
	}

}