package com.dne.ctrip.entity;

import com.dne.core.basic.entity.BaseEntity;
import lombok.Getter;
import lombok.Setter;

/**
 * BMdClaimMailPolicy generated by MyEclipse - Hibernate Tools
 */
@Getter
@Setter
public class CommonMailPolicy extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long mailId;

	private String processType;

	private String mailType;

	private String subject;

	private String tpath;

	private String template;

	private String mailTo;

	public CommonMailPolicy() {

	}
}